config/routes.rb
Rails.application.routes.draw do
  
  root "posts#index"
  get 'logout',   to: 'logins#destroy',  as: 'logout'

  resources :registrations, only: %i[new create]
  resources :posts
  resources :logins,        only: %i[new create destroy]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  
  belongs_to :user
  
  validates :title,   presence: true
  validates :content, presence: true
  
end

app/models/user.rb
class User < ApplicationRecord
  
  has_many  :posts
  
  validates :email,     presence: true, uniqueness: true
  validates :password,  presence: true, length: { minimum: 5 }
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  def find_user
    @user = User.find_by(id: session[:user_id]) if session[:user_id]
  end
  
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  
  before_action :find_user, only: [:new]
  
  def new
    redirect_to root_path if @user
    @user = User.new
  end

  def create
    @user = User.find_by(login_params)
    
    if @user
      flash[:notice] = "Welcome back!"
      session[:user_id] = @user.id
      redirect_to posts_path
    else
      flash[:alert] = "Email and/or Password is incorrect!"
      render  :new, status: :unprocessable_entity
    end
  end
  
  def destroy
    session[:user_id] = nil
    flash[:notice] = "Goodbye, have a great day"
    redirect_to root_path
  end

  
  private
  
  def login_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_action :find_user, only: [:index, :new, :create, :show, :edit]
  before_action :find_post, only: [:show, :edit, :update]
  
  def index
    @posts = Post.all
  end

  def new
    redirect_to new_login_path unless @user
    @post = Post.new
  end
  
  def create
    @new_post = Post.new(post_params)
    @new_post.user_id = @user.id 
    
    if @new_post.save
      flash[:notice] = "Post created"
      redirect_to posts_path
    else
      flash[:alert] = "Could not create post, please try again"
      render  :new, status: :unprocessable_entity
    end
    
  end

  def show
  end

  def edit
    
    if @user.nil? 
      flash[:alert] = "Please login before editing"
      redirect_to new_login_path 
    else
      unless @post.user.id == @user.id
        flash[:alert] = "You are not authorize!"
        redirect_to post_path(@post)
      end
    end 
    
  end
  
  def update
    
    if @post.update(post_params)
      flash[:notice] = "Post updated!"
      redirect_to post_path(@post)
    else
      render :edit, status: :unprocessable_entity
    end
    
  end
  
  private
  
  def post_params
    params.require(:post).permit(:title, :content)
  end
  
  def find_post
    @post = Post.find(params[:id])
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  
  before_action :find_user, only: [:new]
  
  def new
    redirect_to root_path if @user
    @user = User.new
  end

  def create
    @user = User.new(registration_params)
    @user.name = @user.email[/[^@]+/]
    
    if @user.save
      flash[:notice] = "User successfully created, please login"
      redirect_to new_login_path 
    else
      flash[:alert] = "Email and/or Password could not be created!"
      render  :new, status: :unprocessable_entity
    end
    
  end

  private
  
  # def find_user
  #   @existing_user = User.find_by(id: session[:user_id])
  # end
  
  def registration_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleBlog2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-8 px-5 flex flex-col">
	
	  <% if alert %>
		  <div class="px-5 mx-auto">
			  <div class="font-bold mt-8 border-2 border-rose-200 rounded-lg bg-rose-300 text-white p-4"><%= alert %></div>
		  </div>
	  <% end %>
	  
	  <% if notice %>
		  <div class="px-5 mx-auto">
			  <div class="mt-8 border-2 border-lime-200 rounded-lg bg-lime-300 text-gray-600 p-4"><%= notice %></div>
		  </div>
	  <% end %>
	  
      <%= yield %>
	  
    </main>
  </body>
</html>

app/views/logins/new.html.erb
<div class="my-5 mx-auto w-96">
	
	<div class="mb-8">
	    <%= link_to sanitize("&larr; Show all posts"), root_path, 
	        class: "hover:text-blue-400" %>
	</div>
	
	<div>
	  <h1 class="text-3xl text-center font-bold text-orange-600 mb-5">Simple Blog</h1>
	  <h1 class="text-3xl text-center font-bold">LOGIN</h1>
	</div>
	
	<%= form_with model: @user, url: logins_path do |form| %>
	
		<div>
			<%= form.label :email, class: "block mt-8 uppercase" %>
			<%= form.email_field :email, class: "border-gray-600 text-sm rounded-lg 
	focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5" %>
		</div>
		
		<div>
			<%= form.label :password, class: "block mt-8 uppercase" %>
			<%= form.password_field :password, class: "border-gray-600 text-sm rounded-lg 
	focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5" %>
		</div>
		
		<%= form.submit "LOGIN", class: "w-full mt-6 btn-primary mb-8"%>
		
	<% end %>
	
    <%= link_to "Sign Up here!", new_registration_path, 
        class: "flex justify-center mt-6 btn-primary mb-8 bg-slate-600 hover:text-lime-200" %>
</div>

app/views/posts/_form.html.erb
<div>
	<%= post.label :title, class: "block uppercase" %>
	<%= post.text_field :title, class: "mb-8 border-gray-600 text-sm rounded-lg 
				focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5" %>
</div>

<div>
	<%= post.label :content, class: "block uppercase" %>
	<%= post.text_area :content, class: "mb-8 border-gray-600 text-sm rounded-lg 
				focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5" %>
</div>

app/views/posts/_post.html.erb
<tr class="border-b border-gray-200 hover:bg-gray-100">

	<td class="py-3 px-6 text-center">
		<%= link_to post.title, post_path(post), class:"text-teal-800 hover:text-sky-800 cursor-pointer" %>
	</td>

	<td class="py-3 px-6 text-center">
		<%= post.user.name %>
	</td>

	<td class="py-3 px-6 text-center">
		<%= time_ago_in_words(post.created_at) %> ago
	</td>
</tr>

app/views/posts/edit.html.erb
<div class="my-5 w-full flex justify-left">
    <%= link_to sanitize("&larr; Back to post"), post_path(@post), 
        class: "hover:text-blue-400 mb" %>
</div>

	<h1 class="text-center text-3xl font-bold text-orange-600 mb-5">Edit Post</h1>
	
	 <%= form_with model: @post, url: post_path(@post) do |p| %>
	 	
		<%= render 'form', post: p %>
		
		<%= p.submit "Update Post", class: "btn-primary"%>
		
	 <% end %>

app/views/posts/index.html.erb
<div class="my-5 mx-auto w-full">

	<% if @user %>
	  <div class="flex justify-between">
		<div>
			<p>Welcome <%= @user.name%> | <%= link_to "Logout", logout_path, method: :delete, 
				class: "hover:text-blue-400" %></p>
		</div>
		
		<div>
			<%= link_to sanitize("Create a post &rarr;"), new_post_path, class: "hover:text-blue-400" %>
		</div>
	  </div>
	<% else %>
		<div>
	    <%= link_to sanitize("&larr; Login"), new_login_path, 
	        class: "hover:text-blue-400" %>
		</div>

	<% end %>

	
<% if @posts %>

		<h1 class="font-bold text-3xl text-center text-orange-600">All posts</h1>
		
	  	<table class="mt-8 w-full table-auto border-collapse border border-slate-500">
			<thead>
				<tr class="bg-zinc-200 text-gray-600 uppercase text-sm leading-normal">
					<th class="py-3 px-6 text-center">Title</th>
					<th class="py-3 px-6 text-center">Author</th>
					<th class="py-3 px-6 text-center">Created</th>
				</tr>
			</thead>
			<tbody class="text-gray-600 text-sm font-light">
				<%=  render @posts %>
			</tbody>
		
		</table>
		
<% else %>
	
	<div class="w-96 mx-auto">
		<h1 class="font-bold text-4xl text-center mb-8">No posts</h1>
		<%= link_to "Create a post", new_post_path, class:"flex justify-center btn-primary" %>
	</div>
	
<% end %>

</div>

app/views/posts/new.html.erb
<div class="my-5 w-full flex justify-left">
    <%= link_to sanitize("&larr; List all posts"), posts_path, 
        class: "hover:text-blue-400 mb" %>
</div>

	<h1 class="text-center text-3xl font-bold text-orange-600 mb-5">New Post</h1>
	
	 <%= form_with model: @post, url: posts_path do |p| %>
	 
	 	<%= render 'form', post: p %>
		
		<%= p.submit "Create Post", class: "btn-primary"%>
	 <% end %>
	 
	

app/views/posts/show.html.erb
<div>
    <%= link_to sanitize("&larr; Return to posts"), root_path, 
        class: "hover:text-blue-400" %>
</div>

<div class="mt-8">
  <h1 class="mb-8 text-3xl text-center text-orange-600"><%= @post.title %></h1>
  <p><%= @post.content %></p>
</div>

<% if @user %>

	<% if @user.id == @post.user.id %>
		<div class="mt-8 grid justify-items-end">
			<%= link_to sanitize("Edit this post &rarr;"), edit_post_path(@post.id),  class: "hover:text-blue-400" %>
		</div>
	<% end %>
	
<% end %>